@startuml diagramme_uc_super_admin
skinparam linetype ortho

title Cas d'Utilisation - Super Admin

package "Cas d'Utilisation Super Admin" {
  rectangle "UC-SADM-01: Se connecter super admin" as UC_SADM_01
  rectangle "UC-SADM-02: Consulter dashboard global" as UC_SADM_02
  rectangle "UC-SADM-03: Créer agence" as UC_SADM_03
  rectangle "UC-SADM-04: Modifier agence" as UC_SADM_04
  rectangle "UC-SADM-05: Consulter liste agences" as UC_SADM_05
  rectangle "UC-SADM-06: Activer/Désactiver agence" as UC_SADM_06
  rectangle "UC-SADM-07: Créer utilisateur (tous rôles)" as UC_SADM_07
  rectangle "UC-SADM-08: Modifier infos & rôle utilisateur" as UC_SADM_08
  rectangle "UC-SADM-09: Consulter liste utilisateurs" as UC_SADM_09
  rectangle "UC-SADM-10: Bloquer/Débloquer utilisateur" as UC_SADM_10
  rectangle "UC-SADM-11: Gérer tous les envois" as UC_SADM_11
  rectangle "UC-SADM-12: Consulter tous journaux activité" as UC_SADM_12
  rectangle "UC-SADM-13: Gérer paramètres généraux" as UC_SADM_13
}

' --- Relations Logiques ---
UC_SADM_01 --> UC_SADM_02 : "Dashboard"
UC_SADM_02 --> UC_SADM_03
UC_SADM_02 ---> UC_SADM_04
UC_SADM_02 --> UC_SADM_05
UC_SADM_02 ---> UC_SADM_06
UC_SADM_02 --> UC_SADM_07
UC_SADM_02 ---> UC_SADM_08
UC_SADM_02 --> UC_SADM_09
UC_SADM_02 ---> UC_SADM_10
UC_SADM_02 --> UC_SADM_11
UC_SADM_02 ---> UC_SADM_12
UC_SADM_02 --> UC_SADM_13

@enduml