@startuml diagramme_uc_comptable
skinparam linetype ortho

title Cas d'Utilisation - Comptable

package "Cas d'Utilisation Comptable" {
  rectangle "UC-ACC-01: Se connecter comptable" as UC_ACC_01
  rectangle "UC-ACC-02: Consulter dashboard financier" as UC_ACC_02
  rectangle "UC-ACC-03: Gérer & valider paiements" as UC_ACC_03
  rectangle "UC-ACC-04: Gérer facturation" as UC_ACC_04
  rectangle "UC-ACC-05: Exporter données financières" as UC_ACC_05
  rectangle "UC-ACC-06: Consulter & gérer tarifs" as UC_ACC_06
}

' --- Relations Logiques ---
UC_ACC_01 --> UC_ACC_02 : "Dashboard"
UC_ACC_02 --> UC_ACC_03
UC_ACC_02 --> UC_ACC_04
UC_ACC_02 --> UC_ACC_05
UC_ACC_02 --> UC_ACC_06

@enduml