// path: /src/app/layout.tsx
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/components/navigations/footer/Footer";
import React from "react";
import {SessionProvider} from "next-auth/react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className + " d-flex flex-column min-vh-100"} data-theme="dark">
        <SessionProvider>
            <main>{children}</main>
            <Footer/>
        </SessionProvider>
        </body>
        </html>
    );
}
