// path: /src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
// import Header from "@/components/navigations/header/Header";
import Footer from "@/components/navigations/footer/Footer";
import React from "react";
// import 'react-toastify/dist/ReactToastify.css';
// import HeaderWithPathname from "@/components/HeaderWithPathname";
// import HeaderWrapper from "@/components/navigations/header/HeaderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className} data-theme="dark">
        {/*<HeaderWithPathname />*/}

        <main>
            {children}
        </main>
        <Footer />
        </body>
        </html>
    );
}
