import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "@/components/navigations/header/header";
import React from "react";
import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/navigations/footer/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className} data-theme="dark">
        < Header />
        <main>
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    );
}
